/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellIndexRouteImport } from './routes/_shell.index'
import { Route as ShellDatabasesDatabaseIdRouteImport } from './routes/_shell.databases.$databaseId'
import { Route as ShellProjectsProjectIdRouteImport } from './routes/_shell.projects.$projectId'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDatabasesDatabaseIdRoute =
  ShellDatabasesDatabaseIdRouteImport.update({
    id: '/databases/$databaseId',
    path: '/databases/$databaseId',
    getParentRoute: () => ShellRoute,
  } as any)
const ShellProjectsProjectIdRoute = ShellProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/databases/$databaseId': typeof ShellDatabasesDatabaseIdRoute
  '/projects/$projectId': typeof ShellProjectsProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof ShellIndexRoute
  '/databases/$databaseId': typeof ShellDatabasesDatabaseIdRoute
  '/projects/$projectId': typeof ShellProjectsProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/': typeof ShellIndexRoute
  '/_shell/databases/$databaseId': typeof ShellDatabasesDatabaseIdRoute
  '/_shell/projects/$projectId': typeof ShellProjectsProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/databases/$databaseId' | '/projects/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/databases/$databaseId' | '/projects/$projectId'
  id:
    | '__root__'
    | '/_shell'
    | '/_shell/'
    | '/_shell/databases/$databaseId'
    | '/_shell/projects/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/databases/$databaseId': {
      id: '/_shell/databases/$databaseId'
      path: '/databases/$databaseId'
      fullPath: '/databases/$databaseId'
      preLoaderRoute: typeof ShellDatabasesDatabaseIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/projects/$projectId': {
      id: '/_shell/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ShellProjectsProjectIdRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellIndexRoute: typeof ShellIndexRoute
  ShellDatabasesDatabaseIdRoute: typeof ShellDatabasesDatabaseIdRoute
  ShellProjectsProjectIdRoute: typeof ShellProjectsProjectIdRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellIndexRoute: ShellIndexRoute,
  ShellDatabasesDatabaseIdRoute: ShellDatabasesDatabaseIdRoute,
  ShellProjectsProjectIdRoute: ShellProjectsProjectIdRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
